language: python

python:
  - "2.7"

install:
  - pip install coverage coveralls --use-mirrors
  - pip install -r requirements.txt --use-mirrors

script: coverage run tests.py

after_success: coveralls
